
server {
    listen 127.0.0.1:8080;
    listen 127.0.0.1:8081;

    root ./www;
    index index.html;

    client_max_body_size 10000000;
    # error_page 404 /404.html;

    location / {
        allowed_methods GET;

        root ./www;
        index index.html;
        autoindex off;
    }

    location /files/ {
        allowed_methods GET;

        root ./www/files;
        autoindex on;
    }

    location /upload/ {
        allowed_methods POST;

        root ./www;
        upload_enable on;
        upload_store ./www/uploads;
    }

    location /delete/ {
        allowed_methods DELETE;

        root ./www/deletable;
    }

    location /redirect {
        allowed_methods GET;

        return 301 /;
    }

    location /cgi/ {
        allowed_methods GET POST;

        root ./www/cgi;
        cgi_extension .py;
        cgi_pass /usr/bin/python3;
    }

    location /cgi-sh/ {
        allowed_methods GET;
        root ./www/cgi;
        cgi_extension .sh;
        cgi_pass /bin/bash;
    }
    
}

